VirtualBrandWorks-Backend/VirtualBrandWork/Controllers/QuizController.cs
using System.Web.Http;
using Repository;
using Service;
using System.Net.Http;
using System.Net;
using System;
using VirtualBrandWork.Common;
using System.Collections.Generic;
using Repository.Repository;
using VirtualBrandWork.Entity;
using VirtualBrandWork.Entity.ViewModels;
using Service.Interfaces;
using VirtualBrandWork.Filters;
using Newtonsoft.Json;

namespace VirtualBrandWork.Controllers
{
    [JWTAuthenticationFilter]
    [RoutePrefix("api/quiz")]
    public class QuizController : ApiController
    {
        private readonly log4net.ILog logger = log4net.LogManager.GetLogger(typeof(QuizController));
        private readonly IQuizService _quizService;

        public QuizController(IQuizService quizService)
        {
            _quizService = quizService;
        }

        /// <summary>
        /// Add question in quiz
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("AddQuestion")]
        public HttpResponseMessage AddQuestion(QuestionAnswerViewModel questionAnswerViewModel)
        {
            logger.Info($"{Constants.ADD_QUESTION_API} is called");
            try
            {
                Response response = _quizService.AddQuestion(questionAnswerViewModel);
                logger.Info($"{Constants.ADD_QUESTION_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(questionAnswerViewModel, Formatting.Indented)}",ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new HttpError(Constants.INTERNAL_SERVER_ERROR));
            }
        }

        /// <summary>
        /// Add question in quiz
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("SaveQuiz")]
        public HttpResponseMessage SaveQuiz(QuizViewModel quizViewModel)
        {
            logger.Info($"{Constants.SAVE_QUIZ} is called");
            try
            {
                if (string.IsNullOrEmpty(quizViewModel.QuizName))
                    return Request.CreateResponse(HttpStatusCode.BadRequest, new HttpError(Constants.QUIZ_NAME_CANNOT_BE_EMPTY));

                Response response = _quizService.SaveQuiz(quizViewModel);
                logger.Info($"{Constants.SAVE_QUIZ} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(quizViewModel, Formatting.Indented)}",ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new HttpError(Constants.INTERNAL_SERVER_ERROR));
            }
        }

        /// <summary>
        /// Add question in quiz
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("GetQuizDetails")]
        public HttpResponseMessage GetQuizDetails(QuizViewModel quizViewModel)
        {
            logger.Info($"{Constants.GET_QUIZ_DETAILS} is called");
            try
            {
                if (quizViewModel == null || quizViewModel.QuizId == 0)
                    return Request.CreateResponse(HttpStatusCode.BadRequest, new HttpError(Constants.QUIZ_ID_CANNOT_BE_EMPTY));

                QuizViewModel response = _quizService.GetQuizDetails(quizViewModel.QuizId);
                logger.Info($"{Constants.GET_QUIZ_DETAILS} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, new Response() { Data = response, Status = true });
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(quizViewModel, Formatting.Indented)}",ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new HttpError(Constants.INTERNAL_SERVER_ERROR));
            }
        }

        /// <summary>
        /// Add question in quiz
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("GetQuestionDetails")]
        public HttpResponseMessage GetQuestionDetails(QuestionViewModel questionViewModel)
        {
            logger.Info($"{Constants.Get_QUESTION_DETAILS_API} is called");
            try
            {
                if (questionViewModel == null || questionViewModel.QuestionId == 0)
                    return Request.CreateResponse(HttpStatusCode.BadRequest, new HttpError(Constants.QUESTION_ID_CANNOT_BE_EMPTY));

                QuestionAnswerViewModel response = _quizService.GetQuestionDetails(questionViewModel.QuestionId);
                logger.Info($"{Constants.Get_QUESTION_DETAILS_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, new Response() { Data = response, Status = true });
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(questionViewModel, Formatting.Indented)}",ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new HttpError(Constants.INTERNAL_SERVER_ERROR));
            }
        }

        /// <summary>
        /// Update question in quiz
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("UpdateQuestion")]
        public HttpResponseMessage UpdateQuestion(QuestionAnswerViewModel questionAnswerViewModel)
        {
            logger.Info($"{Constants.Update_QUESTION_API} is called");
            try
            {
                if (questionAnswerViewModel == null || questionAnswerViewModel.Question == null || questionAnswerViewModel.Question.QuestionId == 0)
                    return Request.CreateResponse(HttpStatusCode.BadRequest, new HttpError(Constants.QUESTION_ID_CANNOT_BE_EMPTY));

                Response response = _quizService.UpdateQuestion(questionAnswerViewModel);
                logger.Info($"{Constants.Update_QUESTION_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(questionAnswerViewModel, Formatting.Indented)}",ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new HttpError(Constants.INTERNAL_SERVER_ERROR));
            }
        }

        /// <summary>
        /// Delete quiz
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("DeleteQuiz")]
        public HttpResponseMessage DeleteQuiz(QuizViewModel quizViewModel)
        {
            logger.Info($"{Constants.DELET_QUIZ} is called");
            try
            {
                if (quizViewModel == null || quizViewModel.QuizId == 0)
                    return Request.CreateResponse(HttpStatusCode.BadRequest, new HttpError(Constants.QUIZ_ID_CANNOT_BE_EMPTY));

                Response response = _quizService.DeleteQuiz(quizViewModel.QuizId);
                logger.Info($"{Constants.DELET_QUIZ} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(quizViewModel, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new HttpError(Constants.INTERNAL_SERVER_ERROR));
            }
        }

        /// <summary>
        /// Delete question
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("DeleteQuestion")]
        public HttpResponseMessage DeleteQuestion(QuestionViewModel questionViewModel)
        {
            logger.Info($"{Constants.DELETE_QUESTION} is called");
            try
            {
                if (questionViewModel == null || questionViewModel.QuestionId == 0)
                    return Request.CreateResponse(HttpStatusCode.BadRequest, new HttpError(Constants.QUESTION_ID_CANNOT_BE_EMPTY));

                Response response = _quizService.DeleteQuestion(questionViewModel.QuestionId);
                logger.Info($"{Constants.DELETE_QUESTION} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(questionViewModel, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new HttpError(Constants.INTERNAL_SERVER_ERROR));
            }
        }
    }
}

VirtualBrandWorks-Backend/VirtualBrandWork/Controllers/TagController.cs
using Repository.Repository;
using Service;
using Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using VirtualBrandWork.Common;
using VirtualBrandWork.Entity;
using VirtualBrandWork.Entity.ViewModels;
using VirtualBrandWork.Filters;

namespace VirtualBrandWork.Controllers
{
    [JWTAuthenticationFilter]
    [RoutePrefix("api/Tag")]
    public class TagController : ApiController
    {
        private readonly ITagService _tagService;
        private readonly log4net.ILog logger = log4net.LogManager.GetLogger(typeof(TagController));
        public TagController(ITagService tagService)
        {
            _tagService = tagService;
        }


        /// <summary>
        /// get tags list in SelectListItem
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("get_tags")]
        public HttpResponseMessage GetTags()
        {
            logger.Info($"{Constants.GET_TAGS_LIST} is called");
            try
            {
                List<TagViewModel> tags = _tagService.GetTags();
                Response response = new Response { Data = tags, Status = true };
                logger.Info(string.Concat(Constants.GET_TAGS_LIST, " is complete"));
                return Request.CreateResponse(HttpStatusCode.OK, response, Configuration.Formatters.JsonFormatter);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// create a new tag
        /// </summary>
        /// <param name="tag"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("create_tag")]
        public HttpResponseMessage Create(TagViewModel tag)
        {
            logger.Info($"{Constants.CREATE_TAG} is called");
            Response response = new Response();
            if (!ModelState.IsValid)
            {
                response.Message = "One or more entered values are invalid, please check.";
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            try
            {
                bool isExists = _tagService.IsTagExists(tag);
                if (isExists)
                    response.Message = "Tag is already exists with same name";
                else
                {
                    _tagService.Create(tag);
                    response.Status = true;
                }
                logger.Info(string.Concat(Constants.CREATE_TAG, " is complete"));
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        [HttpGet]
        [Route("GetTagSuggestion")]
        public HttpResponseMessage GetTagSuggestion(string suggestion, string type)
        {
            logger.Info("GetTagSuggestion is called");
            try
            {
                List<TagViewModel> tags = _tagService.GetTagSuggestion(type, suggestion, IdentityHelper.GetUserId());
                Response response = new Response
                {
                    Data = tags,
                    Status = tags == null ? false : true
                };
                logger.Info("GetTagSuggestion is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response, Configuration.Formatters.JsonFormatter);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        [HttpGet]
        [Route("GetTagsWithIndustries")]
        public HttpResponseMessage GetTagsWithIndustries()
        {
            List<TagViewModel> tagsWithIndustries = _tagService.GetTagsWithIndustries();
            Response response = new Response
            {
                Data = tagsWithIndustries,
                Status = tagsWithIndustries != null
            };
            return Request.CreateResponse(HttpStatusCode.OK, response, Configuration.Formatters.JsonFormatter);
        }

        [HttpPost]
        [Route("GetTag")]
        public HttpResponseMessage GetTag(TagViewModel model)
        {
            logger.Info("GetTagSuggestion is called");
            try
            {
                var tag = _tagService.GetTagById(model.TagId);
                Response response = new Response
                {
                    Data = tag,
                    Status = tag != null
                };
                logger.Info("GetTagSuggestion is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response, Configuration.Formatters.JsonFormatter);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [Route("edit_tag")]
        public HttpResponseMessage EditTag(TagViewModel model)
        {
            logger.Info("EditTag is called");
            try
            {
                _tagService.EditTag(model);
                Response response = new Response
                {
                    Status = true
                };
                logger.Info("EditTag is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response, Configuration.Formatters.JsonFormatter);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [Route("delete_tag")]
        public HttpResponseMessage DeleteTag(TagViewModel model)
        {
            logger.Info("Delete is called");
            try
            {
                _tagService.Delete(model.TagId);
                Response response = new Response
                {
                    Status = true
                };
                logger.Info("Delete is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response, Configuration.Formatters.JsonFormatter);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }
    }
}

VirtualBrandWorks-Backend/VirtualBrandWork/Views/Shared/_AdminTrainerLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/font.css">
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/media.css">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="~/Content/PreLoader.css" rel="stylesheet" />

    <title>Welcome to Virtual brandworks!</title>
</head>
<body>
    <div class="headerWrap beforeLogin minSize">
        <div class="header d-flex justify-content-between align-items-center">

            <div class="logo">
               <a href="@Url.Action("Index", "Home")"> <img src="~/Images/logo-sml.png" alt="logo"></a>
            </div>

            <div class="rightHead">
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Login
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="@Url.Action("Login","Account")">Login</a>
                        @*<div class="dropdown-divider"></div>
                        <a class="dropdown-item asp" href="@Url.Action("SignUp","Account")">Signup</a>*@

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- render content? -->
    @RenderBody()
    <!-- render content? -->
    <!-- footer? -->
    <div class="footer">
        <p>&copy;Virtualbrandworks.com</p>
        <p>
            <a href="@Url.Action("TermsAndConditions","Home")">Terms and Conditions</a>
            <a href="@Url.Action("PrivacyPolicy","Home")">Privacy Policy</a>
        </p>
    </div>
    <div id="loader-wrapper">
        <div id="loader"></div>
    </div>
    <!-- footer? -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="~/Scripts/jquery-3.2.1.slim.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById("loader-wrapper").style.display = "none";
        };
        //(function ($) {
        //    'use strict';
        //    var $slides = $('[data-slides]');
        //    var images = $slides.data('slides');
        //    var count = images.length;
        //    var slideshow = function () {
        //        $slides
        //          .css('background-image', 'url("' + images[Math.floor(Math.random() * count)] + '")')
        //          .show(0, function () {
        //              setTimeout(slideshow, 2500);
        //          });
        //    };
        //    slideshow();
        //}(jQuery));
    </script>
    @Scripts.Render("~/bundles/jquery")
   @* @Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/jqueryUI")
    @Scripts.Render("~/bundles/JdataTable")
    @RenderSection("scripts", required: false)
</body>
</html>

VirtualBrandWorks-Backend/VirtualBrandWork/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/font.css">
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/media.css">

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/JqueryUI")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/PreLoader.css" rel="stylesheet" />

    <title>Welcome to Virtual brandworks!</title>
</head>
<body>
    <!-- Header -->
    <div class="header afterLogin d-flex justify-content-between align-items-center">
        <div class="logo">
            <img src="~/Images/logo-sml.png" alt="logo">
        </div>
        <div class="rightHead">
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    <!-- Header -->
    <!-- home page -->
    <div class="mainWrapper">
        @if (User.Identity.IsAuthenticated == true)
        {
            <div class="leftContent">
                <div class="sideNav">
                    <div class="toggleBtn">
                        <span class="closeBtn"></span>
                    </div>
                    <ul>
                        <li><a href="@Url.Action("ChangePassword", "Account")"> <span class="ico plylist"></span><small>Change Password</small> </a> </li>
                        <li><a href="@Url.Action("Index", "Subscription")"> <span class="ico compnyContnt"></span><small>Subscription Plan</small> </a> </li>
                        <li class="list">
                            <a class="list-link"><span class="ico mstLib"></span><small>Master Library</small> </a>
                            <ul>
                                <li><a href="@Url.Action("Index", "Categories")"> <span class="ico ep"></span><small>Industry</small> </a> </li>
                                <li><a href="@Url.Action("Index", "MasterFolder")"> <span class="ico vbp"></span><small>Folder</small> </a> </li>
                                <li><a href="@Url.Action("Index", "MasterContent")"> <span class="ico compnyContnt"></span><small>Content</small> </a> </li>
                                <li><a href="@Url.Action("Index", "Quiz")"> <span class="ico ps"></span><small>Quiz</small> </a> </li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Index","Tag")"><span class="ico tg"></span><small>Manage Tags</small> </a> </li>
                        <li><a href="@Url.Action("Index", "UserInformation")"> <span class="ico compnyContnt"></span><small>Manage Users</small> </a> </li>
                    </ul>
                </div>
            </div>
        }
        else
        {

        }
        <div class="rightContent">
            @if (TempData["Success"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @TempData["Success"]
                </div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["Error"]
                </div>
            }
            @RenderBody()
        </div>
    </div>

    <!-- home page -->
    <!-- footer? -->
    <div class="footer">
        <p>&copy;Virtualbrandworks.com</p>
        @*<p>
            <a href="@Url.Action("TermsAndConditions","Home")">Terms and Conditions</a>
            <a href="@Url.Action("PrivacyPolicy","Home")">Privacy Policy</a>
        </p>*@
    </div>
    <!-- footer? -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="~/Scripts/jquery-3.2.1.slim.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="~/Scripts/script.js"></script>

    <div id="loader-wrapper">
        <div id="loader"></div>
    </div>
    <!-- footer? -->
    <script src="~/Scripts/popper.min.js"></script>

    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/select2.js"></script>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryUI")
    @Scripts.Render("~/bundles/JdataTable")

    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById("loader-wrapper").style.display = "none";
        };

        //$('.list').click(function (e) {
        //    e.stopPropagation();
        //    $(this).children().slideToggle();
        //});
    </script>
</body>
</html>


<link href="~/Content/select2.css" rel="stylesheet" />
<script src="~/Scripts/select2.js"></script>