VirtualBrandWorks-Backend/VirtualBrandWork/Controllers/MasterContentController.cs
using Newtonsoft.Json;
using Service.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using VirtualBrandWork.Common;
using VirtualBrandWork.Entity;
using VirtualBrandWork.Entity.ViewModels;
using VirtualBrandWork.Filters;
using VirtualBrandWorks.common;

namespace VirtualBrandWork.Controllers
{
    [JWTAuthenticationFilter]
    [RoutePrefix("api/mastercontent")]
    public class MasterContentController : ApiController
    {
        private readonly IMasterContentService _masterContentService;
        private readonly IAWSS3FileStorage _awsS3FileStorage;
        private readonly log4net.ILog logger = log4net.LogManager.GetLogger(typeof(MasterContentController));

        public MasterContentController(IMasterContentService masterContentService, IAWSS3FileStorage awsS3FileStorage)
        {
            _masterContentService = masterContentService;
            _awsS3FileStorage = awsS3FileStorage;
        }

        /// <summary>
        /// Api to get the list of MasterContent
        /// </summary>
        /// <returns></returns>
        [Route("get_all_contents")]
        public HttpResponseMessage GetAllContents()
        {
            logger.Info($"{Constants.GET_ALL_CONTENT_API} is called");

            try
            {
                List<MasterContentViewModel> masterContents = _masterContentService.GetAllContents();
                Response response = new Response { Data = masterContents, Status = true };
                logger.Info($"{Constants.GET_ALL_CONTENT_API} is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// Api to create a MasterContent , accepts a MasterContent type object in param
        /// </summary>
        /// <param name="content"></param>
        /// <returns></returns>
        [Route("create_content")]
        public HttpResponseMessage Create(MasterContentViewModel content)
        {
            logger.Info($"{Constants.MASTER_CONTENT_CREATE_API} is called");

            if (!ModelState.IsValid)
                return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                _masterContentService.Create(content);
                Response response = new Response() { Status = true };
                logger.Info($"{Constants.MASTER_CONTENT_CREATE_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(content, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// Api to update a particular Master Content
        /// </summary>
        /// <param name="content"></param>
        /// <returns></returns>
        [Route("update_content")]
        public HttpResponseMessage Update(MasterContentViewModel content)
        {
            logger.Info($"{Constants.MASTER_CONTENT_UPDATE_API} is called");

            if (!ModelState.IsValid)
                return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                _masterContentService.Update(content);
                Response response = new Response() { Status = true };
                logger.Info($"{Constants.MASTER_CONTENT_UPDATE_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(content, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// Api to get details of any specififc Content
        /// </summary>
        /// <param name="content"></param>
        /// <returns></returns>
        [Route("details_content")]
        public HttpResponseMessage Details(MasterContentViewModel content)
        {
            logger.Info($"{Constants.MASTER_CONTENT_DETAILS_API} is called");

            if (content.MasterContentId == 0)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);
            }
            try
            {
                MasterContentViewModel masterContentViewModel = _masterContentService.GetContent(content.MasterContentId);
                Response response = new Response() { Data = masterContentViewModel, Status = true };
                logger.Info($"{Constants.MASTER_CONTENT_DETAILS_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(content, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        /// </summary>
        /// <param name="content"></param>
        /// <returns></returns>
        [HttpDelete]
        [Route("delete_content")]
        public HttpResponseMessage Delete(MasterContentViewModel content)
        {
            logger.Info($"{Constants.MASTER_CONTENT_DELETE_API} is called");

            if (content.MasterContentId == 0)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);
            }

            try
            {
                _masterContentService.Delete(content.MasterContentId);
                Response response = new Response() { Status = true };
                logger.Info($"{Constants.MASTER_CONTENT_DELETE_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(content, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// Get master contents
        /// </summary>
        /// <param name="foderId"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("get_contents_by_folder")]
        public HttpResponseMessage GetMasterContentsByFolderId(MasterFolderViewModel masterFolder)
        {
            logger.Info($"{Constants.GET_CONTENTS_BY_FOLDER_API} is called");

            //  if (!ModelState.IsValid)
            //return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                List<ContentViewModel> response = _masterContentService.GetMasterContentsByFolderId(masterFolder.MasterFolderId);
                logger.Info($"{Constants.GET_CONTENTS_BY_FOLDER_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, new Response() { Data = response, Status = true }, Configuration.Formatters.JsonFormatter);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(masterFolder, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// publish or unpublish a content.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("publish")]
        public HttpResponseMessage PubishUnpublishContent(MasterContentViewModel content)
        {
            logger.Info("api/mastercontent/publish is called");

            Response response = new Response();
            if (content.MasterContentId == 0)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);
            }
            try
            {
                int checkPublishOrUnpublish = (int)Constants.PublishedOrUnpublish.ContentNotFound;
                //first create a thumbnail and then set the bit in database for publish if flag is true then only create thumbnail
                if (content.flag)
                {
                    MasterContentViewModel contentExisting = _masterContentService.GetContent(content.MasterContentId);
                    if (contentExisting.ContentUrl.Contains(".mp4") || contentExisting.ContentUrl.Contains(".mov") || contentExisting.ContentUrl.Contains(".3gp"))
                    {
                        var isThumbCreated = _awsS3FileStorage.CreateThumbnailFromFile(contentExisting.ContentUrl, contentExisting.MimeType);
                        if (isThumbCreated)
                        {
                            checkPublishOrUnpublish = _masterContentService.PublishUnpublishContent(content.MasterContentId);
                            response.Status = true;
                        }
                        else
                        {
                            response.Status = false;
                        }
                    }
                    else
                    {
                        checkPublishOrUnpublish = _masterContentService.PublishUnpublishContent(content.MasterContentId);
                        response.Status = true;
                    }
                }
                else
                {
                    checkPublishOrUnpublish = _masterContentService.PublishUnpublishContent(content.MasterContentId);
                    response.Status = true;
                }

VirtualBrandWorks-Backend/VirtualBrandWork/Views/MasterContent/Details.cshtml
@model Repository.ModelClass.MasterContent

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MasterContent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MasterFolderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MasterFolderId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MasterContentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VirtualBrandWorks-Backend/VirtualBrandWork/Views/MasterContent/Index.cshtml
@model IEnumerable<VirtualBrandWork.Entity.ViewModels.MasterContentViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#table_id').DataTable();

        ///initialize ctaegory change
        filterByCategory();

        ///initialize folder change
        filterByFolder();

        ///Load categories
        loadCategory();
    });


    function filterByCategory() {
        $('#ddlCategory').on('change', function () {
            filterCategoryData();
        });
    }

    function filterCategoryData() {
        var table = $('#table_id').DataTable();
        var selectedCategory = $("#ddlCategory option:selected").text();
        var selectedCategoryValue = $("#ddlCategory option:selected").val()

        if (selectedCategory != '' && selectedCategory != 'Select Category') {
            $.fn.dataTable.ext.search.push(
                   function (settings, data, dataIndex) {
                       return IsValueExist(data[2], selectedCategory)
                   }
               );
            table.draw();
            $.fn.dataTable.ext.search.pop();
        }
        else {
            table.columns(2).search("").draw();
        }

        ////Load folders
        loadFolders(selectedCategoryValue == '' ? 0 : selectedCategoryValue);
    }

    function filterByFolder() {
        $('#ddlFolders').on('change', function () {
            filterFolderData();
        });
    }

    function filterFolderData() {
        var table = $('#table_id').DataTable();
        var selectedFolder = $("#ddlFolders option:selected").text();
        var selectedFolderValue = $("#ddlFolders option:selected").val();

        if (selectedFolder != '' && selectedFolder != 'Select Folder') {
            $.fn.dataTable.ext.search.push(
                   function (settings, data, dataIndex) {
                       return IsValueExist(data[3], selectedFolder)
                   }
               );
            table.draw();
            $.fn.dataTable.ext.search.pop();
        }
        else {
            ///if folder not selected
            filterCategoryData();
        }
    }

    function IsValueExist(data, val) {
        var array = data.split(',')
        if (array.indexOf(val) !== -1)
            return true;
        else return false;
    }

    function loadFolders(id) {
        $.ajax({
            url: '../Quiz/GetFoldersByCategoyId',
            data: { categoryId: id },
            success: function (data) {
                var select = $("#ddlFolders");
                select.empty();
                select.append($('<option/>', {
                    value: 0,
                    text: "Select Folder"
                }));
                $.each(data, function (index, itemData) {
                    select.append($('<option/>', {
                        value: itemData.MasterFolderId,
                        text: itemData.Name
                    }));
                });
            },
            error: function (xhr) {
            },
            complete: function (jqXHR, status) {
            }
        });
    }

    function loadCategory() {
        $.ajax({
            url: '../Categories/GetCategories',
            success: function (data) {
                var select = $("#ddlCategory");
                select.empty();
                select.append($('<option/>', {
                    value: "",
                    text: "Select Industry"
                }));
                $.each(data, function (index, itemData) {

                    select.append($('<option/>', {
                        value: itemData.CategoryId,
                        text: itemData.CategoryName
                    }));
                });
                var select = $("#ddlFolders");
                select.empty();
                select.append($('<option/>', {
                    value: 0,
                    text: "Select Folder"
                }));
            },
            error: function (xhr) {
            },
            complete: function (jqXHR, status) {
            }
        });
    }

    function addRequestVerificationToken(data) {
        data.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        return data;
    };

    function Delete(id) {
        if (confirm("Are you sure you want to delete this content?")) {
            $.ajax({
                type: "POST",
                url: '../MasterContent/Delete',
                data: addRequestVerificationToken({ "id": id }),
                success: function (data) {
                    if (data.status == "Success") {
                        location.reload();
                    } else {
                        alert('Issue in delete process.Please contact administrator');
                    }
                }
            ,
                error: function (xhr) {
                },
                complete: function (jqXHR, status) {
                }
            });
        }
    }

    function PublishUnpublishContent(id, flag) {
        document.getElementById("loader-wrapper").style.display = "block";
        $.ajax({
            type: "POST",
            url: '@Url.Action("PublishUnpublishContent", "MasterContent")',
            data: { id: id, flag: flag },
            success: function (data) {
                window.location.href = "@Url.Action("Index", "MasterContent")";
                document.getElementById("loader-wrapper").style.display = "none";
            },
            failure: function (response) {
            },
            error: function (response) {
            }
        });
    }
</script>

<style type="text/css">
    hr {
        padding: 0px !important;
        margin: 0px !important;
        margin-top: 1% !important;
        margin-bottom: 1% !important;
    }

    table.dataTable tbody th, table.dataTable tbody td {
        padding: 2px 10px !important;
    }

        .select-panel {
        background-color: #f1f1f1;
        padding-bottom: 1%;
        padding-top: 1%;
    }
</style>
<div class="pageHeader">
    <div class="navbar justify-content-between align-item-center">
        <h4>Content</h4>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "MasterContent")';return false;" data-toggle="modal" data-target="#myModal">
            Add New
        </button>
    </div>
</div>
<hr />
<div class="row select-panel align-items-end">
    <div class="col-lg-3">
        Filter By
        @Html.DropDownList("ddlCategory", new SelectList(new List<VirtualBrandWork.Entity.ViewModels.CategoryViewModel>()), new { @class = "form-control input-sm" })
    </div>

    <div class="col-lg-3">
        @Html.DropDownList("ddlFolders", new SelectList(new List<VirtualBrandWork.Entity.ViewModels.MasterFolderViewModel>()), new { @class = "form-control input-sm" })
    </div>
</div>
@using (Html.BeginForm("Delete", "MasterContent", FormMethod.Post, new { @id = "deleteform" }))
{
    @Html.AntiForgeryToken()

    <div class="custom-datatable-class content-table">
        <table id="table_id" class="display table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CategoryName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FolderName)
                    </th>
                    <th><P>Actions</P></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FolderName)
                        </td>
                        <td>
                            @if (!item.IsPublished)
                            {
                                <input id="btn-publish" type="button" value="Publish" onclick="PublishUnpublishContent(@item.MasterContentId,true);" class="btn btn-success" />
                            }
                            else
                            {
                                <input id="btn-unpublish" type="button" value="Unpublish" onclick="PublishUnpublishContent(@item.MasterContentId,false);" class="btn btn-danger" />
                            }
                            @if (!item.IsAddDynamicFolder)
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = item.MasterContentId }, new { @class = "btn btn-primary" })
                                <input type="button" value="Delete" onclick="Delete(@item.MasterContentId);" class="btn btn-danger" />
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}