VirtualBrandWorks-Backend/VirtualBrandWork/Controllers/SubscriptionController.cs
using Newtonsoft.Json;
using Service.Interfaces;
using Stripe;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using VirtualBrandWork.Common;
using VirtualBrandWork.Entity;
using VirtualBrandWork.Entity.ViewModels;
using VirtualBrandWork.Filters;
using System.Linq;
using VirtualBrandWork.Notification.Interfaces;

namespace VirtualBrandWork.Controllers
{
    // [JWTAuthenticationFilter]
    [RoutePrefix("api/subscription")]
    public class SubscriptionController : ApiController
    {
        private readonly ISubscriptionService _subscriptionService;
        private readonly IStripePaymentUtility _stripePaymentUtility;
        private readonly IEmailService _emailService;
        private readonly INotificationService _notificationService;
        private readonly log4net.ILog logger = log4net.LogManager.GetLogger(typeof(SubscriptionController));
        public SubscriptionController(ISubscriptionService subscriptionService, IStripePaymentUtility stripePaymentUtility, IEmailService emailService, INotificationService notificationService)
        {
            _subscriptionService = subscriptionService;
            _stripePaymentUtility = stripePaymentUtility;
            _emailService = emailService;
            _notificationService = notificationService;
        }

        // GET api/Subscription/Index
        [HttpGet]
        [Route("index")]
        [AllowAnonymous]
        public HttpResponseMessage Index()
        {
            logger.Info($"{Constants.GET_ALL_SUBSCRIPTION_API} is called");
            try
            {
                IEnumerable<SubscriptionViewModel> subscriptions = _subscriptionService.GetAllSubscription();
                Response response = new Response { Data = subscriptions, Status = true };
                logger.Info($"{Constants.GET_ALL_SUBSCRIPTION_API} is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        // POST api/Subscription/Create
        [HttpPost]
        [Route("create")]
        public HttpResponseMessage Create(SubscriptionViewModel subscription)
        {
            logger.Info($"{Constants.SUBSCRIPTION_CREATE_API} is called");

            if (!ModelState.IsValid)
                return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                _subscriptionService.Create(subscription);
                Response response = new Response() { Status = true };
                logger.Info($"{Constants.SUBSCRIPTION_CREATE_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(subscription, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        // POST api/Subscription/GetSubscription
        [HttpPost]
        [Route("get_subscription")]
        [AllowAnonymous]
        public HttpResponseMessage GetSubscription(SubscriptionViewModel subscription)
        {
            logger.Info($"{Constants.SUBSCRIPTION_DETAILS_API} is called");

            if (subscription.SubscriptionId == 0)
                return Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                SubscriptionViewModel subscriptionViewModel = _subscriptionService.GetSubscriptionById(subscription);
                Response response = new Response() { Data = subscriptionViewModel, Status = true };
                logger.Info($"{Constants.SUBSCRIPTION_DETAILS_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(subscription, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        // POST api/Subscription/Update
        [HttpPost]
        [Route("update")]
        public HttpResponseMessage Update(SubscriptionViewModel model)
        {
            logger.Info($"{Constants.SUBSCRIPTION_UPDATE_API} is called");

            if (!ModelState.IsValid)
                Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                UserMyPlanNotiFicationViewModel updatedInfo = _subscriptionService.Update(model);
                if(updatedInfo.IsPlanNameChanged || updatedInfo.IsPlanDescriptionChanged || updatedInfo.IsNumberOfUsersChanged || updatedInfo.IsMonthlyCostChanged)
                {
                    if(updatedInfo.UsersForMonthlySubscription.Count > 0)
                    {
                        // mail to monthly users
                        _emailService.SendSubscriptionDetailsUpdatedNotificationEmail(updatedInfo, true);
                        var usersToBeNotified = updatedInfo.UsersForMonthlySubscription.Select(u => u.UserId).ToList();
                        _notificationService.SendNotifications(usersToBeNotified, string.Format(Constants.SubscriptionInfoChanged), Constants.SubscriptionChangedTitle);
                    }
                }
                if (updatedInfo.IsPlanNameChanged || updatedInfo.IsPlanDescriptionChanged || updatedInfo.IsNumberOfUsersChanged || updatedInfo.IsAnnualCostChanged)
                {
                    if(updatedInfo.UsersForYearlySubscription.Count > 0)
                    {
                        // mail to yearly users
                        _emailService.SendSubscriptionDetailsUpdatedNotificationEmail(updatedInfo, false);
                        var usersToBeNotified = updatedInfo.UsersForYearlySubscription.Select(u => u.UserId).ToList();
                        _notificationService.SendNotifications(usersToBeNotified, string.Format(Constants.SubscriptionInfoChanged), Constants.SubscriptionChangedTitle);
                    }
                }
                Response response = new Response() { Status = true };
                logger.Info($"{Constants.SUBSCRIPTION_UPDATE_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(model, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        // POST api/Subscription/Delete
        [HttpDelete]
        [Route("delete")]
        public HttpResponseMessage Delete(SubscriptionViewModel subscription)
        {
            logger.Info($"{Constants.SUBSCRIPTION_DELETE_API} is called");

            if (!ModelState.IsValid)
                Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                _subscriptionService.Delete(subscription);
                Response response = new Response() { Status = true };
                logger.Info($"{Constants.SUBSCRIPTION_DELETE_API} is completed");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error($"{ex.Message} {JsonConvert.SerializeObject(subscription, Formatting.Indented)}", ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        [Route("GetSubscriptionListForAdmin")]
        [AllowAnonymous]
        public HttpResponseMessage GetSubscriptionListForAdmin(bool noTrial)
        {
            logger.Info($"{Constants.GET_ALL_SUBSCRIPTION_FOR_ADMIN_API} is called");
            try
            {
                IEnumerable<SubscriptionViewModel> subscriptions = _subscriptionService.GetSubscriptionListForAdmin(noTrial);
                Response response = new Response { Data = subscriptions, Status = true };
                logger.Info($"{Constants.GET_ALL_SUBSCRIPTION_FOR_ADMIN_API} is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }

        [JWTAuthenticationFilter]
        [Route("get_subscription_details_for_company")]
        [HttpPost]
        [AuthorizeUser(Role = "SuperAdmin")]
        public HttpResponseMessage GetSubscriptionDetailsForCompany(CompanyViewModel company)
        {
            logger.Info($"{Constants.GET_ALL_SUBSCRIPTION_FOR_ADMIN_API} is called");

            if (company.CompanyId != 0)
                Request.CreateResponse(HttpStatusCode.BadRequest, Constants.INVALID_ARGUMENT);

            try
            {
                CompanySubscriptionViewModel companySubscriptions = _subscriptionService.GetSubscriptionDetailsForCompany(company.CompanyId);
                Response response = new Response { Data = companySubscriptions, Status = true };
                logger.Info($"{Constants.GET_ALL_SUBSCRIPTION_FOR_ADMIN_API} is complete");
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message, ex);
                return Request.CreateResponse(HttpStatusCode.InternalServerError);
            }
        }
    }
}

VirtualBrandWorks-Backend/VirtualBrandWork/Views/Subscription/Create.cshtml
@model VirtualBrandWork.Entity.ViewModels.SubscriptionViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="pageHeader">
    <div class="navbar justify-content-between align-item-center">
        <h4>Subscription</h4>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal customMinFrm">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PlanName, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.PlanName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlanName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlanDescription, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.TextAreaFor(model => model.PlanDescription, new { htmlAttributes = new { @class = "form-control", @id="txtDesc" } })
                @Html.ValidationMessageFor(model => model.PlanDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfUsers, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.TextBoxFor(model => model.NumberOfUsers, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NumberOfUsers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostForMonthlyBilling, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.CostForMonthlyBilling, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostForMonthlyBilling, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostForAnnualBilling, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.CostForAnnualBilling, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostForAnnualBilling, "", new { @class = "text-danger" })
            </div>
        </div>       
        <div class="form-group">
             @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
             <div>
               @Html.RadioButtonFor(model => model.Status, "false", new { id = "inactive" })
               @Html.Label("inactive", "Inactive")

                 @Html.RadioButtonFor(model => model.Status, "true", new { id = "active" })
                 @Html.Label("active", "Active")
                 <div> 
                      @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                 </div>
            </div>
        </div>
        <div class="form-group">
            <div>
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

VirtualBrandWorks-Backend/VirtualBrandWork/Views/Subscription/Details.cshtml
@model VirtualBrandWork.Entity.ViewModels.SubscriptionViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Subscription</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlanName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlanName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlanDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlanDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfUsers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfUsers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostForMonthlyBilling)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostForMonthlyBilling)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostForAnnualBilling)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostForAnnualBilling)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SubscriptionId }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</p>

VirtualBrandWorks-Backend/VirtualBrandWork/Views/Subscription/Edit.cshtml
@model VirtualBrandWork.Entity.ViewModels.SubscriptionViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #PlanDescription {
        width: 280px !important;
    }
</style>

<div class="pageHeader">
    <div class="navbar justify-content-between align-item-center">
        <h4>Subscription</h4>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    @Html.HiddenFor(h=>h.ProductId)
    @Html.HiddenFor(h => h.PlanId)
    

    <div class="form-horizontal customMinFrm">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SubscriptionId)

        <div class="form-group">
            @Html.LabelFor(model => model.PlanName, htmlAttributes: new { @class = "control-label" })
            <div >
                @Html.EditorFor(model => model.PlanName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlanName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlanDescription, htmlAttributes: new { @class = "control-label" })
            <div >
                @Html.TextAreaFor(model => model.PlanDescription, new { htmlAttributes = new { @class = "form-control", @id = "txtDesc" } })
                @Html.ValidationMessageFor(model => model.PlanDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfUsers, htmlAttributes: new { @class = "control-label" })
            <div >
                @Html.TextBoxFor(model => model.NumberOfUsers, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NumberOfUsers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostForMonthlyBilling, htmlAttributes: new { @class = "control-label" })
            <div >
                @Html.EditorFor(model => model.CostForMonthlyBilling, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostForMonthlyBilling, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostForAnnualBilling, htmlAttributes: new { @class = "control-label" })
            <div >
                @Html.EditorFor(model => model.CostForAnnualBilling, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostForAnnualBilling, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.RadioButtonFor(model => model.Status, "false", new { id = "inactive" })
                @Html.Label("inactive", "Inactive")

                @Html.RadioButtonFor(model => model.Status, "true", new { id = "active" })
                @Html.Label("active", "Active")
                <div>
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div >
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

VirtualBrandWorks-Backend/VirtualBrandWork/Views/Subscription/Index.cshtml
@model IEnumerable<VirtualBrandWork.Entity.ViewModels.SubscriptionViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#table_id').DataTable();
    });

    function addRequestVerificationToken(data) {
        data.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        return data;
    };

    function Delete(id, productId){
        if(confirm("Are you sure you want to delete this Subscription plan?")){
            $.ajax({
                type: "POST",
                url: '../Subscription/Delete',
                data: addRequestVerificationToken({ "id": id , "ProductId": productId}),
                success: function (data) {
                    if (data.status == "Success") {
                        location.reload();
                    } else {
                        alert('Issue in delete process.Please contact administrator');
                    }
                }
            ,
                error: function (xhr) {
                },
                complete: function (jqXHR, status) {
                }
            });
        }
    }
</script>

<style type="text/css">
    hr {
        padding: 0px !important;
        margin: 0px !important;
        margin-top: 1% !important;
        margin-bottom: 1% !important;
    }

    table.dataTable tbody th, table.dataTable tbody td {
        padding: 2px 10px !important;
    }

    .btn {
    width: 100px !important;
    }
</style>
<div class="pageHeader">
    <div class="navbar justify-content-between align-item-center">
        <h4>Subscription Plan</h4>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Subscription")';return false;">
            Add New
        </button>
    </div>
</div>
<hr />
@using (Html.BeginForm("Delete", "Subscription", FormMethod.Post, new { @id = "deleteform" }))
{
    @Html.AntiForgeryToken()
    <div class="custom-datatable-class">
    <table id="table_id" class="display table-bordered table-hover">
        <thead>
            <tr>
                <th width="10%">
                    @Html.DisplayNameFor(model => model.PlanName)
                </th>
                <th width="30%">
                    @Html.DisplayNameFor(model => model.PlanDescription)
                </th>
                <th width="10%">
                    @Html.DisplayNameFor(model => model.NumberOfUsers)
                </th>
                <th width="15%">
                    @Html.DisplayNameFor(model => model.CostForMonthlyBilling)
                </th>
                <th width="15%">
                    @Html.DisplayNameFor(model => model.CostForAnnualBilling)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th width="20%">

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PlanName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PlanDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberOfUsers)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CostForMonthlyBilling)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CostForAnnualBilling)
                    </td>
                    <td>
                        @{
                            string parameterValue = item.Status ? "Active" : "Inactive";
                        }
                        @Html.DisplayFor(modelItem => (parameterValue))
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.SubscriptionId, pId = item.PlanId }, new { @class = "btn btn-primary" }) 
                        <input type="button" value="Delete" onclick="Delete(@item.SubscriptionId, '@item.ProductId');" class="btn btn-danger" />
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
}